name = "BARON"
uuid = "2e2ca445-9e14-5b13-8677-4410f177f82b"
repo = "https://github.com/joehuchette/BARON.jl.git"
version = "0.6.5"

[deps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[compat]
JuMP = "~0.21.1"
MathOptInterface = "~0.9.5"
julia = "1"

[extras]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JuMP", "Test"]
